<?php
/**
 * Workation Castle theme bootstrap.
 *
 * Fork target. Pediment (parent) is read-only; your blocks,
 * theme.json overrides and child-specific PHP live here.
 *
 * @package PedimentChild
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

if ( ! defined( 'PEDIMENT_CHILD_DIR' ) ) {
	define( 'PEDIMENT_CHILD_DIR', __DIR__ );
}
if ( ! defined( 'PEDIMENT_CHILD_VERSION' ) ) {
	define( 'PEDIMENT_CHILD_VERSION', '0.13.0' ); // Bumped on release; see x-release-please-version.
}

// One-click theme updates from GitHub Releases (no manual zip uploads).
if ( file_exists( __DIR__ . '/vendor/autoload.php' ) ) {
	require_once __DIR__ . '/vendor/autoload.php';
}
// UpdateToken (token storage/precedence/encryption) must load before
// ThemeUpdater::register(), which resolves the token through it.
require_once __DIR__ . '/inc/UpdateToken.php';
require_once __DIR__ . '/inc/ThemeUpdater.php';
\PedimentChild\ThemeUpdater::register();
// Settings → Pediment Theme → Updates: configure/rotate the update token from
// wp-admin instead of wp-config.php. Admin-only.
if ( is_admin() ) {
	require_once __DIR__ . '/inc/settings-updates.php';
}

// Content seed: rebuild pages from theme block patterns (`wp pediment-child seed`
// or Tools → Seed content). Keeps the homepage in version control, not just the DB.
require_once __DIR__ . '/inc/seed.php';

// GDPR consent manager: gates third-party embeds + analytics behind opt-in.
require_once __DIR__ . '/inc/Consent.php';

// Photo gallery: custom post type + taxonomy for the filterable /photos grid.
require_once __DIR__ . '/inc/Photos.php';

// Activities: public custom post type for the /activities/ page and its singles.
require_once __DIR__ . '/inc/Activities.php';

// Check-in: private CPT + REST endpoint + Brevo email for guest registration.
require_once __DIR__ . '/inc/CheckIn.php';
\PedimentChild\CheckIn::register();
require_once __DIR__ . '/inc/Brevo.php';

// Section block render helpers (also loaded by individual block render.php files,
// but required here so helpers are available outside the block rendering path,
// e.g. in unit tests and direct template includes).
require_once __DIR__ . '/inc/WorkationSections.php';
require_once __DIR__ . '/inc/EstateMap.php';
require_once __DIR__ . '/inc/AvailabilityForm.php';
require_once __DIR__ . '/inc/PrimaryNav.php';

// Section copy for pages stored before that copy moved into the pattern markup.
// Must load after WorkationSections.php, whose render helpers consume the
// attributes it supplies. Transitional — see the file header.
require_once __DIR__ . '/inc/LegacyBlockCopy.php';

// Polylang: declare wp_navigation translatable so each language binds its own
// Primary menu. Must load after PrimaryNav.php, which is what consumes the effect.
require_once __DIR__ . '/inc/Polylang.php';

// Per-language Primary menus, generated by the content seed. Must load after
// PrimaryNav.php (nav source + marker) and Polylang.php (which is what makes
// wp_navigation translatable in the first place).
require_once __DIR__ . '/inc/NavTranslations.php';

// Legacy URL redirects: 301 retired paths (renamed/re-nested/removed pages) to
// their new homes so old inbound links and search results keep working.
require_once __DIR__ . '/inc/Redirects.php';
\PedimentChild\Redirects::register();

/**
 * Register every block in the given directory (defaults to build/blocks).
 *
 * Named distinctly from the parent's pediment_register_blocks() — both
 * functions.php files load for a child theme, so an identical name would
 * fatal-redeclare.
 *
 * @param string|null $base_dir Directory containing block subfolders.
 */
function pediment_child_register_blocks( $base_dir = null ) {
	$is_default_dir = ( null === $base_dir || '' === $base_dir );
	if ( $is_default_dir ) {
		$base_dir = PEDIMENT_CHILD_DIR . '/build/blocks';
	}

	if ( ! is_dir( $base_dir ) ) {
		// A missing build/blocks unregisters every block at once: the editor
		// reports each section as unsupported and the front end renders empty,
		// with nothing in the logs. Flag it so the cause is visible in wp-admin
		// rather than inferred from a blank page. Only the real build dir is
		// flagged; callers passing an explicit path (tests) are not.
		if ( $is_default_dir ) {
			pediment_child_flag_missing_build();
		}
		return;
	}

	$registry = WP_Block_Type_Registry::get_instance();
	foreach ( glob( $base_dir . '/*', GLOB_ONLYDIR ) as $block_dir ) {
		$manifest = $block_dir . '/block.json';
		if ( ! file_exists( $manifest ) ) {
			continue;
		}
		$meta = json_decode( file_get_contents( $manifest ), true );
		if ( is_array( $meta ) && isset( $meta['name'] ) && $registry->is_registered( $meta['name'] ) ) {
			continue;
		}
		register_block_type( $block_dir );
	}
}

add_action(
	'init',
	function () {
		pediment_child_register_blocks();
	}
);

/**
 * Record that the theme's built blocks are missing, and surface it in wp-admin.
 *
 * The usual cause is a theme package built without `npm run build`, or an
 * update that installed GitHub's auto-generated source zip (which excludes the
 * gitignored `build/`) instead of the release asset. See inc/ThemeUpdater.php.
 */
function pediment_child_flag_missing_build() {
	// Idempotent: init can fire more than once in CLI/eval contexts, and two
	// copies of the same notice help nobody.
	if ( has_action( 'admin_notices', 'pediment_child_render_missing_build_notice' ) ) {
		return;
	}
	add_action( 'admin_notices', 'pediment_child_render_missing_build_notice' );
}

/**
 * Render the "no blocks are registered" notice.
 *
 * Kept separate from pediment_child_flag_missing_build() so the capability gate
 * is exercisable on its own.
 */
function pediment_child_render_missing_build_notice() {
	if ( ! current_user_can( 'switch_themes' ) ) {
		return;
	}
	?>
	<div class="notice notice-error">
		<p>
			<strong><?php esc_html_e( 'Workation Castle theme: no blocks are registered.', 'pediment-child' ); ?></strong>
		</p>
		<p>
			<?php
			printf(
				/* translators: %s: absolute path to the theme's build/blocks directory. */
				esc_html__( 'The built block directory %s is missing, so every section block is unavailable and pages using them render empty. Reinstall the theme from the workation-castle-theme.zip release asset (not the "Source code" zip).', 'pediment-child' ),
				'<code>' . esc_html( PEDIMENT_CHILD_DIR . '/build/blocks' ) . '</code>'
			);
			?>
		</p>
	</div>
	<?php
}

/**
 * Retire the generic parent `pediment/cta` block.
 *
 * The site uses one closing call-to-action everywhere: the branded
 * `pediment-child/workation-closing` section from the homepage bottom
 * (full-bleed image, headline, Check availability / Ask for a custom offer,
 * Instagram link). The parent's plain `pediment/cta` band is off-brand, so it
 * is unregistered here to keep it out of the inserter and prevent accidental
 * reuse in new pages. Runs after registration (priority 20). No pattern ships
 * `wp:pediment/cta`, so nothing renders blank.
 */
add_action(
	'init',
	function () {
		$registry = WP_Block_Type_Registry::get_instance();
		if ( $registry->is_registered( 'pediment/cta' ) ) {
			unregister_block_type( 'pediment/cta' );
		}
	},
	20
);

add_action(
	'wp_enqueue_scripts',
	function () {
		$style_path = get_stylesheet_directory() . '/style.css';
		wp_enqueue_style(
			'pediment-child',
			get_stylesheet_directory_uri() . '/style.css',
			array(),
			file_exists( $style_path ) ? (string) filemtime( $style_path ) : wp_get_theme()->get( 'Version' )
		);

		$header_js_path = get_stylesheet_directory() . '/assets/js/header.js';
		wp_enqueue_script(
			'workation-castle-header',
			get_stylesheet_directory_uri() . '/assets/js/header.js',
			array(),
			file_exists( $header_js_path ) ? (string) filemtime( $header_js_path ) : wp_get_theme()->get( 'Version' ),
			true
		);

		$reveal_js_path = get_stylesheet_directory() . '/assets/js/reveal.js';
		wp_enqueue_script(
			'workation-castle-reveal',
			get_stylesheet_directory_uri() . '/assets/js/reveal.js',
			array(),
			file_exists( $reveal_js_path ) ? (string) filemtime( $reveal_js_path ) : wp_get_theme()->get( 'Version' ),
			true
		);

		$lightbox_js_path = get_stylesheet_directory() . '/assets/js/lightbox.js';
		wp_enqueue_script(
			'workation-castle-lightbox',
			get_stylesheet_directory_uri() . '/assets/js/lightbox.js',
			array(),
			file_exists( $lightbox_js_path ) ? (string) filemtime( $lightbox_js_path ) : wp_get_theme()->get( 'Version' ),
			true
		);

		$photo_filter_js_path = get_stylesheet_directory() . '/assets/js/photo-filter.js';
		wp_enqueue_script(
			'workation-castle-photo-filter',
			get_stylesheet_directory_uri() . '/assets/js/photo-filter.js',
			array(),
			file_exists( $photo_filter_js_path ) ? (string) filemtime( $photo_filter_js_path ) : wp_get_theme()->get( 'Version' ),
			true
		);

		$booking_newtab_js_path = get_stylesheet_directory() . '/assets/js/booking-newtab.js';
		wp_enqueue_script(
			'workation-castle-booking-newtab',
			get_stylesheet_directory_uri() . '/assets/js/booking-newtab.js',
			array(),
			file_exists( $booking_newtab_js_path ) ? (string) filemtime( $booking_newtab_js_path ) : wp_get_theme()->get( 'Version' ),
			true
		);

		$range_picker_js_path = get_stylesheet_directory() . '/assets/js/range-picker.js';
		wp_enqueue_script(
			'workation-castle-range-picker',
			get_stylesheet_directory_uri() . '/assets/js/range-picker.js',
			array(),
			file_exists( $range_picker_js_path ) ? (string) filemtime( $range_picker_js_path ) : wp_get_theme()->get( 'Version' ),
			true
		);
		wp_localize_script( 'workation-castle-range-picker', 'wcRangePicker', pediment_child_range_picker_l10n() );

		$estate_map_js_path = get_stylesheet_directory() . '/assets/js/estate-map.js';
		wp_enqueue_script(
			'workation-castle-estate-map',
			get_stylesheet_directory_uri() . '/assets/js/estate-map.js',
			array(),
			file_exists( $estate_map_js_path ) ? (string) filemtime( $estate_map_js_path ) : wp_get_theme()->get( 'Version' ),
			true
		);

		// Activity locator maps (Leaflet) — only on single activity pages.
		if ( defined( 'PEDIMENT_CHILD_ACTIVITY_CPT' ) && is_singular( PEDIMENT_CHILD_ACTIVITY_CPT ) ) {
			wp_enqueue_style(
				'leaflet',
				'https://unpkg.com/leaflet@1.9.4/dist/leaflet.css',
				array(),
				'1.9.4'
			);
			wp_enqueue_script(
				'leaflet',
				'https://unpkg.com/leaflet@1.9.4/dist/leaflet.js',
				array(),
				'1.9.4',
				true
			);

			$activity_map_js_path = get_stylesheet_directory() . '/assets/js/activity-map.js';
			wp_enqueue_script(
				'workation-castle-activity-map',
				get_stylesheet_directory_uri() . '/assets/js/activity-map.js',
				array( 'leaflet' ),
				file_exists( $activity_map_js_path ) ? (string) filemtime( $activity_map_js_path ) : wp_get_theme()->get( 'Version' ),
				true
			);
		}
	}
);

add_action(
	'after_setup_theme',
	function () {
		add_theme_support( 'editor-styles' );
		add_editor_style( 'style.css' );
	}
);

/**
 * Mark the document as JS-enabled before paint so entrance animations can hide
 * their targets without a flash of content. Printed early in <head>; the
 * reveal stylesheet only hides elements under `html.js`, and reveal.js removes
 * the class again if it can't animate (no IntersectionObserver / reduced motion).
 */
add_action(
	'wp_head',
	function () {
		echo "<script>document.documentElement.classList.add('js');</script>\n";
	},
	1
);

/**
 * Output the site favicon (the Workation Castle logo mark).
 *
 * Emitted on the front end, the admin and the login screen so the brand mark
 * shows everywhere. Uses the SVG mark, which scales crisply at any size.
 */
function pediment_child_favicon() {
	$href = get_theme_file_uri( 'assets/images/favicon.svg' );
	printf(
		'<link rel="icon" href="%1$s?v=%2$s" type="image/svg+xml">' . "\n",
		esc_url( $href ),
		esc_attr( PEDIMENT_CHILD_VERSION )
	);
}
add_action( 'wp_head', 'pediment_child_favicon' );
add_action( 'admin_head', 'pediment_child_favicon' );
add_action( 'login_head', 'pediment_child_favicon' );

/**
 * Flag pages that have no full-bleed hero behind the fixed header.
 *
 * The site header is designed to overlay a cinematic hero — white logo and nav
 * on a transparent background. On pages without such a hero (most inner pages,
 * archives, 404, search) that white-on-light is unreadable, and the content
 * slides up under the fixed header. This adds a `no-hero` body class that the
 * stylesheet keys both fixes off (solid header + top padding), so the behaviour
 * is generic and content-driven rather than configured per page. A page counts
 * as having a hero when it contains the workation-hero or page-hero block —
 * both render a full-bleed photo the transparent header can overlay.
 *
 * @param string[] $classes Body classes.
 * @return string[]
 */
function pediment_child_body_class( $classes ) {
	$has_hero = false;
	if ( is_singular() ) {
		$post = get_queried_object();
		if ( $post instanceof WP_Post ) {
			$has_hero = has_block( 'pediment-child/workation-hero', $post )
				|| has_block( 'pediment-child/page-hero', $post );
		}
	}
	if ( ! $has_hero ) {
		$classes[] = 'no-hero';
	}
	return $classes;
}
add_filter( 'body_class', 'pediment_child_body_class' );

/**
 * Resolve the %PEDIMENT_CHILD_THEME_URI% placeholder in static template parts.
 *
 * Template-part HTML files (header, footer) can't run PHP, so they reference
 * theme assets such as the brand logo through this token. Swapping it for the
 * real stylesheet URI at render time keeps the markup portable: the theme
 * directory is named after the deploy, never hard-coded.
 */
add_filter(
	'render_block_core/html',
	function ( $content ) {
		if ( false === strpos( $content, '%PEDIMENT_CHILD_THEME_URI%' ) ) {
			return $content;
		}
		return str_replace(
			'%PEDIMENT_CHILD_THEME_URI%',
			esc_url( get_stylesheet_directory_uri() ),
			$content
		);
	}
);

/**
 * Keep the theme-file `header` template part canonical.
 *
 * The parent theme's seed (pediment_seed_header_template_part) unconditionally
 * inserts an editable, DB-backed `header` wp_template_part, which otherwise
 * shadows this child's parts/header.html — the branded header with the
 * transparent-on-scroll behaviour. The parent exposes no hook to skip that
 * step, so instead of deleting DB rows (which a re-seed would recreate) we
 * hide the DB copy from template-part resolution. parts/header.html then wins
 * in every environment, surviving re-seeds and stray Site Editor edits.
 *
 * Two paths resolve a template part, so both are intercepted:
 *  - the front end (render_block_core_template_part) runs its own WP_Query
 *    keyed on post_name__in — caught via `posts_pre_query`;
 *  - get_block_template() (REST / editor single fetch) — caught via
 *    `pre_get_block_template`.
 */
add_filter(
	'posts_pre_query',
	function ( $posts, $query ) {
		if ( 'wp_template_part' !== $query->get( 'post_type' ) ) {
			return $posts;
		}
		if ( in_array( 'header', (array) $query->get( 'post_name__in' ), true ) ) {
			return array(); // No DB row -> core falls back to parts/header.html.
		}
		return $posts;
	},
	10,
	2
);

add_filter(
	'pre_get_block_template',
	function ( $block_template, $id, $template_type ) {
		if ( 'wp_template_part' !== $template_type ) {
			return $block_template;
		}
		$parts = explode( '//', $id, 2 );
		if ( count( $parts ) < 2 || get_stylesheet() !== $parts[0] || 'header' !== $parts[1] ) {
			return $block_template;
		}
		$file_template = get_block_file_template( $id, $template_type );
		return $file_template ? $file_template : $block_template;
	},
	10,
	3
);
