<?php
/**
 * Title: Reviews
 * Slug: pediment-child/reviews
 * Categories: pediment-child
 * Description: Guest reviews landing page — the full list of guest reviews.
 * Inserter: no
 */
// phpcs:ignoreFile -- block pattern content (verbatim block markup).
?>
<!-- wp:pediment-child/page-hero {"eyebrow":"Guest reviews","headline":"What our guests say","lead":"In their own words — guests who came to the Workation Castle to work, unwind, or gather with family and friends. Reviews originally left in several languages, translated to English where needed.","imageAlt":"Aerial view of the castle hamlet above Lago di Piano with the mountains beyond","align":"full"} /-->
<!-- wp:pediment-child/workation-reviews {"align":"full","eyebrow":"Guest reviews","headline":"Every review, in full."} -->
<!-- wp:pediment-child/workation-review {"text":"Wonderful place! We did enjoy a lot! Wonderful place for holidays and work! Wonderful people, wonderful area, restaurants as well in the area are really wonderful! The castle is great, is like to go back many years ago and enjoy the nature! Would hardly recommend to everyone! Congratulations to owners, who create this wonderful place! Thanks","title":"Eloisa R."} /-->
<!-- wp:pediment-child/workation-review {"text":"The kitchen is well equipped, the house is large, the garden has a wonderful view, it is very quiet, the parking is not far away, there are plenty of sun loungers, a barbecue, and it is also suitable for large groups. There are a few restaurants within walking distance. Lago di Piano can also be reached on foot, as can Lake Lugano. We stayed with two families, each in a holiday apartment — it was a wonderful holiday.","title":"Kathrin K."} /-->
<!-- wp:pediment-child/workation-review {"text":"The atmosphere of the old walls, the view from the terrace… A great and well-thought-out concept, also for larger families, groups and for working; a very well-equipped kitchen. A beautiful hiking trail that runs around the lake directly through the grounds; a great location for the lakes, cycling and hiking trails.","title":"Nicole R."} /-->
<!-- wp:pediment-child/workation-review {"text":"Castello di Carlazzo — a beautiful gem, with its original fabric and very tastefully renovated parts of the building. Generous spaces for private use and open areas for getting to know other guests. WiFi is available everywhere in the building. The surroundings and the view are a dream, especially in the morning at sunrise. Shops and supermarkets are within walking distance in the immediate vicinity.","title":"Daniel V."} /-->
<!-- wp:pediment-child/workation-review {"text":"The Castello is truly the perfect place for a workation! The office rooms are spacious and very tastefully furnished. The view is wonderful — all the greenery, the mountains and the small lake within walking distance. On top of that, Jonas is a very kind host; communication was excellent from start to finish. I'll gladly come again!","title":"Simone S."} /-->
<!-- wp:pediment-child/workation-review {"text":"We really loved the exceptional location of the holiday apartment. The closeness to nature and above all the quiet were wonderful. The apartment itself also lacked nothing. The modern furnishings are a great contrast to the old walls. We were especially taken with the garden and its wonderful view over Lago di Piano. You can go for lovely walks. Shops are nearby. By car you reach Lago di Lugano in Porlezza in a few minutes… Getting into the apartment with the code was no problem at all, and communication with Jonas was otherwise very pleasant and trouble-free. A perfect holiday.","title":"Maria L."} /-->
<!-- wp:pediment-child/workation-review {"text":"The terrace, quietness, view on the mountains and the animals on the plain below. The convenient location close to a bus stop. And the host was very accommodating, which was highly appreciated by us as a family with a young child.","title":"Philippe R."} /-->
<!-- wp:pediment-child/workation-review {"text":"Quiet location, away from the hustle and bustle of Lake Como. Tastefully furnished. Straightforward key handover. Very nice hosts.","title":"Alexandros P."} /-->
<!-- wp:pediment-child/workation-review {"text":"A wonderful and very relaxing place to work or take a holiday. The Workation Castle sits idyllically on a small hill by Lago di Piano, between Lake Lugano and Lake Como. The house and the shared workspaces are superbly equipped. Everything is very tasteful, brand new and very well thought out… from the dish soap to the coffee beans! … In the work area there are many rooms available, and everything has a very distinctive charm with its mix of old walls and new furnishings. A supermarket, bakery and a few pizzerias are within an easy walk… The WiFi is great, and communication with the owners is quick.","title":"Anna-Lena F."} /-->
<!-- wp:pediment-child/workation-review {"text":"The location is perfect! right between lake Como and lake Lugano with a bonus small lake 5 minutes from the location. The apartment is in the castle/fortification which takes you back in time, it's simply amazing. The building is old yet inside you have all the modern amenities (dishwasher/washing machine, fully equipped kitchen etc). Plenty of free parking on the property (something rare in Italy). The co-working space exceeds expectations, it's not just a random room with a table but rather multiple rooms with different purposes which are perfectly fit for both big team events and working in quiet. No hidden fees or surprises...","title":"Alexander M."} /-->
<!-- wp:pediment-child/workation-review {"text":"The place is magnificent. It's close to both Lake Como and Lake Lugano, in a very beautiful natural setting, with a view of the mountains and a small lake where you can swim, five minutes away by car. It's ideal. The welcome and communication with Jonas are easy and pleasant. The apartment is spotless, very well equipped, with pleasant décor. Basic essentials, and more, are provided. There is a terrace and a shared garden with a beautiful view of the mountains. Its location lets you both relax in the greenery and easily explore the surrounding lakes. I recommend it!!!","title":"Manuelle B."} /-->
<!-- wp:pediment-child/workation-review {"text":"An authentic location and a lovely project by Jonas and his Italian in-laws. We felt very welcome. Clean apartment, nice little garden, and a good location. There are lots of things to see and do in the immediate area. Wonderful to swim at the little beach nearby.","title":"Liesbeth L."} /-->
<!-- wp:pediment-child/workation-review {"text":"The apartment is very clean and fully equipped (kitchen appliances, bathrooms, washing machine), and you can also use the shared spaces. The castle sits on a hill. The climb was a little challenging, but the view is fantastic. In the garden you can enjoy the view from the chairs provided. There are supermarkets and restaurants nearby. Jonas had good tips for walks in the area.","title":"Irma S."} /-->
<!-- wp:pediment-child/workation-review {"text":"The house is idyllically situated. Arriving at the old castle is beautiful. The house itself is modern, stylish and comfortable inside. All the rooms were clean, tidy and well cared for. The view from the terrace garden is phenomenal: deer and sheep walk through the meadow in front of you, mountains all around, and you can see both Lake Piano and Lake Lugano. There is plenty of space and privacy. The house is also centrally located in the Como and Lugano area for visiting little towns and wonderful mountain walks. You can swim in the clear Lago di Piano after a short and lovely walk of less than 20 minutes. Contact with host Jonas was good and pleasant. The photos on the website matched reality. In short, a perfect house for a fantastic holiday. We enjoyed every single day!","title":"Corinne O."} /-->
<!-- wp:pediment-child/workation-review {"text":"When we arrived and saw the view, we were sold immediately. Gorgeous! We had the part with three bedrooms and three bathrooms; it was clean and all the amenities were amply provided. Contact with the host was very pleasant. Questions were answered quickly. In short, a top location in beautiful Italy.","title":"Ed K."} /-->
<!-- /wp:pediment-child/workation-reviews -->
