<?php
/**
 * Baseline photo manifest for the one-time seed.
 *
 * Each entry: url (source image), alt, category (term slug), order (menu_order).
 * Harvested from the live Elementor gallery at workationcastle.com/photos/.
 * Consumed by inc/seed.php; after seeding, photos are managed in wp-admin.
 *
 * @package Workation
 */

return array(
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1728-scaled.jpeg',
		'alt'      => 'Casa Galbiga',
		'category' => 'casa-galbiga',
		'order'    => 10,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1708-scaled.jpeg',
		'alt'      => 'The courtyard',
		'category' => 'casa-galbiga',
		'order'    => 20,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1311-scaled.jpeg',
		'alt'      => 'Casa Galbiga Entrance',
		'category' => 'casa-galbiga',
		'order'    => 30,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2288-scaled.jpeg',
		'alt'      => 'The Kitchen',
		'category' => 'casa-galbiga',
		'order'    => 40,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2287-scaled.jpeg',
		'alt'      => 'The Kitchen',
		'category' => 'casa-galbiga',
		'order'    => 50,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/12/8B822EEA-6604-48BE-AB77-1D445059316E_1_105_c.jpeg',
		'alt'      => 'The door to the terrace',
		'category' => 'casa-galbiga',
		'order'    => 60,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/05/IMG_1511-scaled.jpeg',
		'alt'      => 'The Terrace',
		'category' => 'casa-galbiga',
		'order'    => 70,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2275-scaled.jpeg',
		'alt'      => 'Bedroom #1',
		'category' => 'casa-galbiga',
		'order'    => 80,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2274-scaled.jpeg',
		'alt'      => 'Bedroom #1',
		'category' => 'casa-galbiga',
		'order'    => 90,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_2277-1-scaled.jpeg',
		'alt'      => 'Bedroom #2',
		'category' => 'casa-galbiga',
		'order'    => 100,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2276-scaled.jpeg',
		'alt'      => 'Bedroom #2',
		'category' => 'casa-galbiga',
		'order'    => 110,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1509-scaled.jpeg',
		'alt'      => 'Bedroom #3',
		'category' => 'casa-galbiga',
		'order'    => 120,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1510-scaled.jpeg',
		'alt'      => 'Bedroom #3',
		'category' => 'casa-galbiga',
		'order'    => 130,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/Galbiga-Bad.jpg',
		'alt'      => 'Bathroom #1',
		'category' => 'casa-galbiga',
		'order'    => 140,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2273-scaled.jpeg',
		'alt'      => 'Bathroom #2',
		'category' => 'casa-galbiga',
		'order'    => 150,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2284-scaled.jpeg',
		'alt'      => 'Bathroom #3',
		'category' => 'casa-galbiga',
		'order'    => 160,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1449-scaled.jpeg',
		'alt'      => 'Casa Tremezzon (on the left)',
		'category' => 'casa-tremezzo',
		'order'    => 170,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2260-scaled.jpeg',
		'alt'      => 'Living room',
		'category' => 'casa-tremezzo',
		'order'    => 180,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2261-scaled.jpeg',
		'alt'      => 'Living room',
		'category' => 'casa-tremezzo',
		'order'    => 190,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2263-scaled.jpeg',
		'alt'      => 'Living room',
		'category' => 'casa-tremezzo',
		'order'    => 200,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2264-scaled.jpeg',
		'alt'      => 'Kitchen',
		'category' => 'casa-tremezzo',
		'order'    => 210,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2265-scaled.jpeg',
		'alt'      => 'Kitchen',
		'category' => 'casa-tremezzo',
		'order'    => 220,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2241-scaled.jpeg',
		'alt'      => 'Upstairs',
		'category' => 'casa-tremezzo',
		'order'    => 230,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2247-scaled.jpeg',
		'alt'      => 'Bedroom #1',
		'category' => 'casa-tremezzo',
		'order'    => 240,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2248-scaled.jpeg',
		'alt'      => 'Bedroom #1',
		'category' => 'casa-tremezzo',
		'order'    => 250,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2249-scaled.jpeg',
		'alt'      => 'Bedroom #2',
		'category' => 'casa-tremezzo',
		'order'    => 260,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2250-scaled.jpeg',
		'alt'      => 'Bedroom #2',
		'category' => 'casa-tremezzo',
		'order'    => 270,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2242-scaled.jpeg',
		'alt'      => 'Bathroom',
		'category' => 'casa-tremezzo',
		'order'    => 280,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2243-scaled.jpeg',
		'alt'      => 'Bathroom',
		'category' => 'casa-tremezzo',
		'order'    => 290,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/05/IMG_1487-scaled.jpeg',
		'alt'      => 'View from the terrace',
		'category' => 'casa-tremezzo',
		'order'    => 300,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_2186-scaled.jpeg',
		'alt'      => 'Sala Mirandola - The meeting room',
		'category' => 'workspace',
		'order'    => 310,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2160-scaled.jpeg',
		'alt'      => 'The small office for two people',
		'category' => 'workspace',
		'order'    => 320,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2155-scaled.jpeg',
		'alt'      => 'The larger office for four people',
		'category' => 'workspace',
		'order'    => 330,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1492-scaled.jpeg',
		'alt'      => 'The Bar - Community kitchen',
		'category' => 'workspace',
		'order'    => 340,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1493-scaled.jpeg',
		'alt'      => 'The Bar - Community kitchen',
		'category' => 'workspace',
		'order'    => 350,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_2152-1-scaled.jpeg',
		'alt'      => 'The fireplace room',
		'category' => 'workspace',
		'order'    => 360,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1491-scaled.jpeg',
		'alt'      => 'The fireplace room',
		'category' => 'workspace',
		'order'    => 370,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1490-scaled.jpeg',
		'alt'      => 'A small room for phone calls',
		'category' => 'workspace',
		'order'    => 380,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2199-scaled.jpeg',
		'alt'      => 'The office bathroom',
		'category' => 'workspace',
		'order'    => 390,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1857-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 400,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1292-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 410,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/08/IMG_2171-1-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 420,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1987-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 430,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_0870-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 440,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_2009-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 450,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_2392-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 460,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/Workation_Castle_Roofs-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 470,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/Workation_Castle_Lamp-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 480,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/08/IMG_0589-scaled.jpeg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 490,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/Workation_Castle_Piano_Lake.jpg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 500,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/12/Castello-towards-Lugano.jpg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 510,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/11/Castello_Carlazzo_-00014.jpg',
		'alt'      => 'Garden & Castle',
		'category' => 'garden-castle',
		'order'    => 520,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/09/IMG_0531-scaled.jpeg',
		'alt'      => 'Lake Piano',
		'category' => 'surroundings',
		'order'    => 530,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/45ED7B0C-A9A3-4CE7-B66E-75E81CA9B5F2_1_105_c.jpeg',
		'alt'      => 'Lake Piano',
		'category' => 'surroundings',
		'order'    => 540,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/5625846B-5A86-4E2F-90CB-81D80390B5D5_1_105_c.jpeg',
		'alt'      => 'Lake Lugano',
		'category' => 'surroundings',
		'order'    => 550,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/E7005B2E-6E44-4B81-9DFE-152BAF47354E_1_105_c.jpeg',
		'alt'      => 'Lake Lugano',
		'category' => 'surroundings',
		'order'    => 560,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/E8687033-EFDF-410B-BEA1-D092B3A4C857_1_105_c.jpeg',
		'alt'      => 'Lake Como',
		'category' => 'surroundings',
		'order'    => 570,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/12/Bellagio_dal_traghetto_-_panoramio.jpg',
		'alt'      => 'Bellagio (Lake Como)',
		'category' => 'surroundings',
		'order'    => 580,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/IMG_1896-scaled.jpeg',
		'alt'      => 'Surroundings',
		'category' => 'surroundings',
		'order'    => 590,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/09/PXL_20210630_132600351.MP_-scaled.jpg',
		'alt'      => 'Val Sanagra',
		'category' => 'surroundings',
		'order'    => 600,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/09/IMG_1355-scaled.jpeg',
		'alt'      => 'Val Sanagra',
		'category' => 'surroundings',
		'order'    => 610,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/09/IMG_1354-scaled.jpeg',
		'alt'      => 'Val Sanagra',
		'category' => 'surroundings',
		'order'    => 620,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/09/IMG_5947.jpeg',
		'alt'      => 'Val Sanagra',
		'category' => 'surroundings',
		'order'    => 630,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2023/09/IMG_5944.jpeg',
		'alt'      => 'Val Sanagra',
		'category' => 'surroundings',
		'order'    => 640,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/09/DSC_0583-scaled.jpg',
		'alt'      => 'View from Mount Galbiga',
		'category' => 'surroundings',
		'order'    => 650,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/09/IMG_0302-scaled.jpeg',
		'alt'      => 'Surroundings',
		'category' => 'surroundings',
		'order'    => 660,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/12/IMG_1261-scaled.jpeg',
		'alt'      => 'Lake Como Beach',
		'category' => 'surroundings',
		'order'    => 670,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/12/IMG_0624-scaled.jpeg',
		'alt'      => 'Surroundings',
		'category' => 'surroundings',
		'order'    => 680,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/318BF151-3F1E-4E74-9CB3-9D86561B2B90_1_105_c.jpeg',
		'alt'      => 'Surroundings',
		'category' => 'surroundings',
		'order'    => 690,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/327420FD-FC24-42D1-B4E5-8BB240D70C91_1_105_c.jpeg',
		'alt'      => 'Surroundings',
		'category' => 'surroundings',
		'order'    => 700,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/C62C2BE9-E21D-4142-911B-0C1BDCBDDB43_1_105_c.jpeg',
		'alt'      => 'View from the garden',
		'category' => 'surroundings',
		'order'    => 710,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/0F395E91-4CCC-4EBD-B289-88C078B16B43_1_105_c.jpeg',
		'alt'      => 'Surroundings',
		'category' => 'surroundings',
		'order'    => 720,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2024/01/3C116871-D7A8-48B2-9841-46620D89846E_1_105_c.jpeg',
		'alt'      => 'Surroundings',
		'category' => 'surroundings',
		'order'    => 730,
	),
	array(
		'url'      => 'https://workationcastle.com/wp-content/uploads/2022/09/Cusino.jpeg',
		'alt'      => 'Surroundings',
		'category' => 'surroundings',
		'order'    => 740,
	),
);
