#!/usr/bin/env node
/**
 * Block-catalog generator.
 *
 * Pure core (buildCatalog/extractWrapperClass/parsePreservedNotes) is unit
 * tested. The CLI gathers parent block.json from the running wp-env (read-only)
 * and child block.json from src/blocks, then writes docs/PEDIMENT-BLOCKS.md.
 *
 * Run: npm run blocks:catalog   (requires wp-env running)
 */
import { readFile, writeFile, readdir } from 'node:fs/promises';
import { execFileSync } from 'node:child_process';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const NOTE_MARKER = '_(add guidance)_';

export function extractWrapperClass(renderPhp) {
  if (!renderPhp) return null;
  const m = renderPhp.match(/starter-[a-z0-9-]+/);
  return m ? m[0] : null;
}

export function parsePreservedNotes(existingDoc) {
  const notes = {};
  if (!existingDoc) return notes;
  const lines = existingDoc.split('\n');
  let current = null;
  for (const line of lines) {
    const h = line.match(/^## (\S+)/);
    if (h) { current = h[1]; continue; }
    const u = line.match(/^\*\*Use when:\*\*\s+(.*)$/);
    if (u && current) { notes[current] = u[1].trim(); current = null; }
  }
  return notes;
}

function attrLine(name, def) {
  const type = def && def.type ? def.type : 'unknown';
  return `  - \`${name}\` (${type})`;
}

export function buildCatalog(records, existingDoc) {
  const notes = parsePreservedNotes(existingDoc);
  const sorted = [...records].sort((a, b) =>
    a.blockJson.name.localeCompare(b.blockJson.name));

  const out = [];
  out.push('# Pediment block catalog');
  out.push('');
  out.push('> Generated by `npm run blocks:catalog`. Edit only the **Use when** notes —');
  out.push('> everything else is overwritten on regeneration. Do not hand-edit other fields.');
  out.push('');

  for (const { source, blockJson, renderPhp } of sorted) {
    const cls = extractWrapperClass(renderPhp);
    const note = notes[blockJson.name] || NOTE_MARKER;
    out.push(`## ${blockJson.name}`);
    out.push('');
    out.push(`**${blockJson.title || ''}** — ${blockJson.description || ''}`.trim());
    out.push('');
    out.push(`**Source:** ${source}`);
    if (cls) out.push(`**Wrapper class:** \`${cls}\``);
    out.push(`**Use when:** ${note}`);
    out.push('');
    const attrs = blockJson.attributes || {};
    if (Object.keys(attrs).length) {
      out.push('**Attributes:**');
      for (const [name, def] of Object.entries(attrs)) out.push(attrLine(name, def));
      out.push('');
    }
    const align = blockJson.supports && blockJson.supports.align;
    if (align) { out.push(`**Align:** ${align.join(', ')}`); out.push(''); }
  }
  return out.join('\n');
}

const PARENT_GLOB = 'wp-content/themes/pediment/build/blocks';
const DELIM_FILE = '@@@FILE:';
const DELIM_RENDER = '@@@RENDER:';

// Read parent block.json + render.php out of the running wp-env (read-only).
function gatherParentRecords() {
  const script =
    `for d in ${PARENT_GLOB}/*/; do ` +
    `echo "${DELIM_FILE}$d"; cat "$d/block.json" 2>/dev/null; ` +
    `echo; echo "${DELIM_RENDER}$d"; cat "$d/render.php" 2>/dev/null; echo; done`;
  let raw;
  try {
    raw = execFileSync('npx', ['wp-env', 'run', 'cli', 'sh', '-c', script],
      { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (e) {
    throw new Error('Could not read parent blocks from wp-env. Is it running? ' +
      'Run `npm run env:start` first.\n' + (e.stderr || e.message));
  }
  const records = [];
  // Split on the FILE delimiter; ignore wp-env banner text before the first one.
  const chunks = raw.split(DELIM_FILE).slice(1);
  for (const chunk of chunks) {
    const [, jsonAndRest = ''] = chunk.match(/^.*?\n([\s\S]*)$/) || [];
    const [jsonPart = '', renderPart = ''] = jsonAndRest.split(DELIM_RENDER);
    const renderPhp = renderPart.replace(/^.*?\n/, '');
    try {
      const blockJson = JSON.parse(jsonPart.trim());
      records.push({ source: 'parent', blockJson, renderPhp });
    } catch { /* skip non-JSON noise */ }
  }
  return records;
}

async function gatherChildRecords(repoRoot) {
  const base = join(repoRoot, 'src', 'blocks');
  const records = [];
  let dirs = [];
  try { dirs = await readdir(base, { withFileTypes: true }); } catch { return records; }
  for (const d of dirs) {
    if (!d.isDirectory()) continue;
    try {
      const blockJson = JSON.parse(await readFile(join(base, d.name, 'block.json'), 'utf8'));
      let renderPhp = '';
      try { renderPhp = await readFile(join(base, d.name, 'render.php'), 'utf8'); } catch {}
      records.push({ source: 'child', blockJson, renderPhp });
    } catch { /* dir without a valid block.json */ }
  }
  return records;
}

async function main() {
  const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
  const docPath = join(repoRoot, 'docs', 'PEDIMENT-BLOCKS.md');
  let existing = '';
  try { existing = await readFile(docPath, 'utf8'); } catch {}
  const records = [...gatherParentRecords(), ...await gatherChildRecords(repoRoot)];
  if (!records.length) throw new Error('No blocks found — aborting (would clobber the catalog).');
  await writeFile(docPath, buildCatalog(records, existing) + '\n', 'utf8');
  console.log(`Wrote ${records.length} blocks to docs/PEDIMENT-BLOCKS.md`);
}

if (import.meta.main) {
  main().catch((e) => { console.error(e.message); process.exit(1); });
}
